const SHOE_LIST = 'SHOE_LIST';
const SHOE_LIST_REQUEST_START = 'SHOE_LIST_REQUEST_START';
const SHOE_LIST_REQUEST_FAIL = 'SHOE_LIST_REQUEST_FAIL'
const SHOE_CREATE = 'SHOE_CREATE'
const SHOE_DELETE = 'SHOE_DELETE'
const ADD_SHOE_TO_COLORWAY = 'ADD_SHOE_TO_COLORWAY'
const REMOVE_SHOE_TO_COLORWAY = 'REMOVE_SHOE_TO_COLORWAY'
const AUCTION_DELETE = 'AUCTION_DELETE'
const ADD_AUCTION_TO_SHOE = 'ADD_AUCTION_TO_SHOE'

const types = {
    SHOE_LIST,
    SHOE_LIST_REQUEST_START,
    SHOE_LIST_REQUEST_FAIL,
    SHOE_CREATE,
    SHOE_DELETE,
    ADD_SHOE_TO_COLORWAY,
    REMOVE_SHOE_TO_COLORWAY,
    AUCTION_DELETE,
    ADD_AUCTION_TO_SHOE
};

export default types;