const STORE_LIST = 'STORE_LIST';
const STORE_LIST_REQUEST_START = 'STORE_LIST_REQUEST_START';
const STORE_LIST_REQUEST_FAIL = 'STORE_LIST_REQUEST_FAIL'
const STORE_CREATE = 'STORE_CREATE'
const STORE_DELETE = 'STORE_DELETE'
const AUCTION_DELETE = 'AUCTION_DELETE'
const ADD_AUCTION_TO_SHOP = 'ADD_AUCTION_TO_SHOP'


const types = {
    STORE_LIST,
    STORE_LIST_REQUEST_START,
    STORE_LIST_REQUEST_FAIL,
    STORE_CREATE,
    STORE_DELETE,
    AUCTION_DELETE,
    ADD_AUCTION_TO_SHOP
};

export default types;