const AUCTION_LIST = 'AUCTION_LIST';
const AUCTION_LIST_REQUEST_START = 'AUCTION_LIST_REQUEST_START';
const AUCTION_LIST_REQUEST_FAIL = 'AUCTION_LIST_REQUEST_FAIL'
const AUCTION_CREATE = 'AUCTION_CREATE'
const AUCTION_DELETE = 'AUCTION_DELETE'
const ADD_AUCTION_TO_SHOP = 'ADD_AUCTION_TO_SHOP'
const ADD_AUCTION_TO_SHOE = 'ADD_AUCTION_TO_SHOE'

const types = {
    AUCTION_LIST,
    AUCTION_LIST_REQUEST_START,
    AUCTION_LIST_REQUEST_FAIL,
    AUCTION_CREATE,
    AUCTION_DELETE,
    ADD_AUCTION_TO_SHOP,
    ADD_AUCTION_TO_SHOE
};

export default types;