const COLORWAY_LIST = 'COLORWAY_LIST';
const COLORWAY_LIST_REQUEST_START = 'COLORWAY_LIST_REQUEST_START';
const COLORWAY_LIST_REQUEST_FAIL = 'COLORWAY_LIST_REQUEST_FAIL'
const COLORWAY_CREATE = 'COLORWAY_CREATE'
const COLORWAY_DELETE = 'COLORWAY_DELETE'

const types = {
    COLORWAY_LIST,
    COLORWAY_LIST_REQUEST_START,
    COLORWAY_LIST_REQUEST_FAIL,
    COLORWAY_CREATE,
    COLORWAY_DELETE
};

export default types;